name: Continuos Integration (CI)

on:
  push:
    branches: [ "main", "staging", "ci-cd" ]
  pull_request:
    branches: [ "main", "staging", "ci-cd" ]
  workflow_dispatch:

jobs:
  build:
    name: Build, Lint, and SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Menjalankan Linter (Checkstyle) dan Tests
      # CI akan otomatis gagal jika linter menemukan pelanggaran (sesuai konfigurasi build.gradle)
      - name: Run Lint and Tests
        run: ./gradlew check jacocoTestReport

      # Analisis SonarCloud
      # CI akan gagal jika token salah atau proses analisis gagal
      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonar \
            -Dsonar.projectKey=advprog-2026-kki3-project_individual-preparation \
            -Dsonar.organization=advprog-2026-kki3-project \
            -Dsonar.host.url=https://sonarcloud.io
